---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjobdemo
  labels:
    purpose: cronjobdemo
spec:
  schedule: '*/5 * * * *'
  jobTemplate:
    metadata:
      labels:
        purpose: jobdemo
    spec:
      backoffLimit: 3
      template:
        metadata:
          labels:
            app: batchdemo
        spec:
          restartPolicy: OnFailure
          containers:
            - name: batchdemo
              image: alpine
              command:
                - sleep
                - 10s