---
apiVersion: v1
kind: Pod
metadata:
  name: resource-requests
spec:
  containers:
    - image: jenkins/jenkins:lts-jdk11
      name: jenkins
      ports:
        - containerPort: 8080
          protocol: TCP
      resources:
        requests:
          cpu: "250m"
          memory: "256Mi"
      