---
java_package: java-11-openjdk
group: tomcat
user: tomcat
shell: /bin/false
homedir: /opt/tomcat
tomcat_major_version: 10
tomcat_version: 10.1.9
tomcat_user_name: qtdevops
tomcat_user_pwd: qtdevops
tomcat_context_valve_allow: ".*"

