---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-dynamic-vol
  labels:
    app: mysql
    layer: db
spec:
  containers:
    - name: mysql
      image: mysql:8
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: mysql-pvol
          mountPath: /var/lib/mysql
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_USER
          value: qtdevops
        - name: MYSQL_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
  volumes:
    - name: mysql-pvol
      persistentVolumeClaim:
        claimName: mysql-pvc
