---
apiVersion: v1
kind: Service
metadata:
  name: activity6-svc
spec:
  selector:
    app: jenkins
  type: NodePort
  ports:
    - nodePort: 32700
      targetPort: 8080
      port: 8080
      protocol: TCP