---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod-config
spec:
  containers:
    - name: exercise1
      image: alpine
      command: 
        - sleep
        - 1d
      env:
        - name: EXTRA_PARAM
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: extra-param
      volumeMounts:
        - name: config-volume
          mountPath: /config
  volumes:
    - name: config-volume
      configMap:
        name: my-config