---
- name: flush handlers demo
  hosts: all
  tasks:
    - name: print something
      ansible.builtin.file:
        path: "/tmp/handle1"
        state: touch
      notify:
        - handle1
        - handle2
    - name: Force all notified handlers to run at this point, not waiting for normal sync points
      ansible.builtin.meta: flush_handlers
    - name: print something again
      ansible.builtin.file:
        path: "/tmp/handle2"
        state: touch
      notify:
        - handle1
        - handle2
  handlers:
    - name: handle1
      ansible.builtin.debug:
        msg: "handle1"
    - name: handle2
      ansible.builtin.debug:
        msg: "handle2"
    