---
apiVersion: v1
kind: Pod
metadata:
  name: health-check-demo
  labels:
    purpose: health-check
spec:
  containers:
    - name: nginx
      image: nginx:1.21
      ports:
        - containerPort: 80
          protocol: TCP
      livenessProbe:
        httpGet:
          path: /
          port: 80
        initialDelaySeconds: 5
        timeoutSeconds: 2
        periodSeconds: 15
        failureThreshold: 5
      readinessProbe:
        httpGet:
          path: /
          port: 80
        periodSeconds: 10
        successThreshold: 3
        failureThreshold: 3
        