---
apiVersion: v1
kind: Pod
metadata:
  name: init-demo
  labels:
    purpose: init-container
spec:
  containers:
    - name: nginx
      image: nginx:1.21
      ports:
        - containerPort: 80
          protocol: TCP
  initContainers:
    - name: init-1
      image: alpine
      command: ['sh', '-c', 'sleep 30s']
    - name: init-2
      image: alpine
      command: ['sh', '-c', 'sleep 30s']