---
apiVersion: batch/v1
kind: Job
metadata:
  name: oneshot
  labels:
    type: oneshot
spec:
  template:
    metadata:
      labels:
        type: downloadjob
    spec:
      containers:
        - name: job
          image: alpine
          command:
            - sleep
            - 30s
      restartPolicy: OnFailure