---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-azure-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-premium
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pvol-demo
spec:
  containers:
    - name: mysql-contianer
      image: mysql:8-debian
      ports:
        - containerPort: 3306
          protocol: TCP
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: qtdevops
        - name: MYSQL_PASSWORD
          value: qtdevops
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-vol
  volumes:
    - name: mysql-vol
      persistentVolumeClaim:
        claimName: mysql-azure-claim
        readOnly: false        